### ISSUE TITLE
On reloading the app, the tabs state is erased and the tabs are reset

### ISSUE THREAD

**Issue by welcometodailykit** [dailykit/react-editor#3]
As a user, I would want to be able to store the tab state while reloading and maybe even when the tab is closed and opened again. So, either the tab state should be stored inside the browser cache or a server side cache such as redis

**Comment by prvnbist** [comment]
Resolved in - [Added: Local State Mgmt & Tabs Persistence](https://github.com/dailykit/react-editor/commit/577a02d5eb83ff42dea6a64e72cfbb347fa18a3d)
